name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd tic-tac-toe-app
          npm install

      - name: Build project
        run: |
          cd tic-tac-toe-app
          npm run build

      - name: Deploy to server
        run: |
          echo "$DEPLOY_KEY" > deploy_key && chmod 600 deploy_key
          # Ladda upp dist-mappen till servern med rsync
          rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" tic-tac-toe-app/dist/ yourusername@46.101.221.97:~/tic-tac-toe-app/dist/
          # Kopiera filerna till rätt plats på servern med sudo
          ssh -o StrictHostKeyChecking=no -i deploy_key yourusername@46.101.221.97 'sudo cp -r ~/tic-tac-toe-app/dist/* /var/www/tic-tac-toe/'
          echo "Deploy completed!"
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
